/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportatorRouteImport } from './routes/transportator'
import { Route as SoferRouteImport } from './routes/sofer'
import { Route as CerereRouteImport } from './routes/cerere'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComandaIdRouteImport } from './routes/comanda.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const TransportatorRoute = TransportatorRouteImport.update({
  id: '/transportator',
  path: '/transportator',
  getParentRoute: () => rootRouteImport,
} as any)
const SoferRoute = SoferRouteImport.update({
  id: '/sofer',
  path: '/sofer',
  getParentRoute: () => rootRouteImport,
} as any)
const CerereRoute = CerereRouteImport.update({
  id: '/cerere',
  path: '/cerere',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandaIdRoute = ComandaIdRouteImport.update({
  id: '/comanda/$id',
  path: '/comanda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cerere': typeof CerereRoute
  '/sofer': typeof SoferRoute
  '/transportator': typeof TransportatorRoute
  '/admin/users': typeof AdminUsersRoute
  '/comanda/$id': typeof ComandaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cerere': typeof CerereRoute
  '/sofer': typeof SoferRoute
  '/transportator': typeof TransportatorRoute
  '/admin/users': typeof AdminUsersRoute
  '/comanda/$id': typeof ComandaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cerere': typeof CerereRoute
  '/sofer': typeof SoferRoute
  '/transportator': typeof TransportatorRoute
  '/admin/users': typeof AdminUsersRoute
  '/comanda/$id': typeof ComandaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cerere'
    | '/sofer'
    | '/transportator'
    | '/admin/users'
    | '/comanda/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cerere'
    | '/sofer'
    | '/transportator'
    | '/admin/users'
    | '/comanda/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cerere'
    | '/sofer'
    | '/transportator'
    | '/admin/users'
    | '/comanda/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CerereRoute: typeof CerereRoute
  SoferRoute: typeof SoferRoute
  TransportatorRoute: typeof TransportatorRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ComandaIdRoute: typeof ComandaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transportator': {
      id: '/transportator'
      path: '/transportator'
      fullPath: '/transportator'
      preLoaderRoute: typeof TransportatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sofer': {
      id: '/sofer'
      path: '/sofer'
      fullPath: '/sofer'
      preLoaderRoute: typeof SoferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerere': {
      id: '/cerere'
      path: '/cerere'
      fullPath: '/cerere'
      preLoaderRoute: typeof CerereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comanda/$id': {
      id: '/comanda/$id'
      path: '/comanda/$id'
      fullPath: '/comanda/$id'
      preLoaderRoute: typeof ComandaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CerereRoute: CerereRoute,
  SoferRoute: SoferRoute,
  TransportatorRoute: TransportatorRoute,
  AdminUsersRoute: AdminUsersRoute,
  ComandaIdRoute: ComandaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
