/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoferRouteImport } from './routes/sofer'
import { Route as CererileMeleRouteImport } from './routes/cererile-mele'
import { Route as CerereRouteImport } from './routes/cerere'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransportatorIndexRouteImport } from './routes/transportator.index'
import { Route as TransportatorCurseleMeleRouteImport } from './routes/transportator.cursele-mele'
import { Route as TransportatorCereriRouteImport } from './routes/transportator.cereri'
import { Route as ComandaIdRouteImport } from './routes/comanda.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const SoferRoute = SoferRouteImport.update({
  id: '/sofer',
  path: '/sofer',
  getParentRoute: () => rootRouteImport,
} as any)
const CererileMeleRoute = CererileMeleRouteImport.update({
  id: '/cererile-mele',
  path: '/cererile-mele',
  getParentRoute: () => rootRouteImport,
} as any)
const CerereRoute = CerereRouteImport.update({
  id: '/cerere',
  path: '/cerere',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportatorIndexRoute = TransportatorIndexRouteImport.update({
  id: '/transportator/',
  path: '/transportator/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportatorCurseleMeleRoute =
  TransportatorCurseleMeleRouteImport.update({
    id: '/cursele-mele',
    path: '/cursele-mele',
    getParentRoute: () => TransportatorRoute,
  } as any)
const TransportatorCereriRoute = TransportatorCereriRouteImport.update({
  id: '/cereri',
  path: '/cereri',
  getParentRoute: () => TransportatorRoute,
} as any)
const ComandaIdRoute = ComandaIdRouteImport.update({
  id: '/comanda/$id',
  path: '/comanda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cerere': typeof CerereRoute
  '/cererile-mele': typeof CererileMeleRoute
  '/sofer': typeof SoferRoute
  '/admin/users': typeof AdminUsersRoute
  '/comanda/$id': typeof ComandaIdRoute
  '/transportator/cereri': typeof TransportatorCereriRoute
  '/transportator/cursele-mele': typeof TransportatorCurseleMeleRoute
  '/transportator/': typeof TransportatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cerere': typeof CerereRoute
  '/cererile-mele': typeof CererileMeleRoute
  '/sofer': typeof SoferRoute
  '/admin/users': typeof AdminUsersRoute
  '/comanda/$id': typeof ComandaIdRoute
  '/transportator/cereri': typeof TransportatorCereriRoute
  '/transportator/cursele-mele': typeof TransportatorCurseleMeleRoute
  '/transportator': typeof TransportatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cerere': typeof CerereRoute
  '/cererile-mele': typeof CererileMeleRoute
  '/sofer': typeof SoferRoute
  '/admin/users': typeof AdminUsersRoute
  '/comanda/$id': typeof ComandaIdRoute
  '/transportator/cereri': typeof TransportatorCereriRoute
  '/transportator/cursele-mele': typeof TransportatorCurseleMeleRoute
  '/transportator/': typeof TransportatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cerere'
    | '/cererile-mele'
    | '/sofer'
    | '/admin/users'
    | '/comanda/$id'
    | '/transportator/cereri'
    | '/transportator/cursele-mele'
    | '/transportator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cerere'
    | '/cererile-mele'
    | '/sofer'
    | '/admin/users'
    | '/comanda/$id'
    | '/transportator/cereri'
    | '/transportator/cursele-mele'
    | '/transportator'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cerere'
    | '/cererile-mele'
    | '/sofer'
    | '/admin/users'
    | '/comanda/$id'
    | '/transportator/cereri'
    | '/transportator/cursele-mele'
    | '/transportator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CerereRoute: typeof CerereRoute
  CererileMeleRoute: typeof CererileMeleRoute
  SoferRoute: typeof SoferRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ComandaIdRoute: typeof ComandaIdRoute
  TransportatorIndexRoute: typeof TransportatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sofer': {
      id: '/sofer'
      path: '/sofer'
      fullPath: '/sofer'
      preLoaderRoute: typeof SoferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cererile-mele': {
      id: '/cererile-mele'
      path: '/cererile-mele'
      fullPath: '/cererile-mele'
      preLoaderRoute: typeof CererileMeleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerere': {
      id: '/cerere'
      path: '/cerere'
      fullPath: '/cerere'
      preLoaderRoute: typeof CerereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportator/': {
      id: '/transportator/'
      path: '/transportator'
      fullPath: '/transportator/'
      preLoaderRoute: typeof TransportatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportator/cursele-mele': {
      id: '/transportator/cursele-mele'
      path: '/cursele-mele'
      fullPath: '/transportator/cursele-mele'
      preLoaderRoute: typeof TransportatorCurseleMeleRouteImport
      parentRoute: typeof TransportatorRoute
    }
    '/transportator/cereri': {
      id: '/transportator/cereri'
      path: '/cereri'
      fullPath: '/transportator/cereri'
      preLoaderRoute: typeof TransportatorCereriRouteImport
      parentRoute: typeof TransportatorRoute
    }
    '/comanda/$id': {
      id: '/comanda/$id'
      path: '/comanda/$id'
      fullPath: '/comanda/$id'
      preLoaderRoute: typeof ComandaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CerereRoute: CerereRoute,
  CererileMeleRoute: CererileMeleRoute,
  SoferRoute: SoferRoute,
  AdminUsersRoute: AdminUsersRoute,
  ComandaIdRoute: ComandaIdRoute,
  TransportatorIndexRoute: TransportatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
